# Generated by Django 3.2.5 on 2021-07-20 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phot',
            new_name='Photo',
        ),
    ]
